- Makefile
- include/osm2ttl/config/Config.h
- include/osm2ttl/config/Constants.h
- include/osm2ttl/ttl/Constants.h
- src/config/Config.cpp
- src/osm/GeometryHandler.cpp
- src/ttl/Writer.cpp
- tests/E2E.cpp
- tests/config/Config.cpp
- tests/osm/GeometryHandler.cpp
Changes name of predicate to better reflect that ogc:contains/ogc:intersects is only between area and nonarea objects.
Remove --add-inverse-relation-direction
contains -> contains_nonarea
intersects -> intersects_nonarea
> Add _nonarea suffix to ogc:contains and ogc:intersects

- include/osm2ttl/config/Config.h
- include/osm2ttl/config/Constants.h
- src/config/Config.cpp
- src/osm/FactHandler.cpp
- tests/config/Config.cpp
- tests/osm/FactHandler.cpp
This PR adds a new command line option `--add-node-envelope` which stores the bounding box for each `node`. This bounding box repeats the same coordinates multiple times.
> Add option for node envelopes

- include/osm2rdf/osm/TagList.h
- include/osm2rdf/osm/Way.h
Add missing boost header to `TagList.h` and `Way.h`, thus fixing the omission of these includes in libboost1.74 (will be fixed again in 1.75 or 1.76, but we don't have that yet on Ubuntu 20.04).
> Add headers so that it compiles with libboost1.74-dev

- include/osm2rdf/osm/FactHandler.h
- include/osm2rdf/ttl/Constants.h
- src/osm/FactHandler.cpp
- src/ttl/Writer.cpp
- tests/E2E.cpp
With this PR, a tag like "brand:wikidata=Q524757" gets translated into a relation `<node> <osm:brand:wikidata> wd:Q524757`, similar to a tag like `wikidata=Q524757`. Note that "brand:wikidata=Q524757"  is *not* translated into `<node> <osm:wikidata> wd:Q524757`, as there might be multiple wikidata IDs (one for the brand, one for the building, etc).
Wikipedia tags are handled exactly the same.
> Handle keys suffixed with :wikidata and :wikipedia like wikidata and wikipedia keys

- src/osm/Node.cpp
This PR adds a missing `#include "boost/geometry.hpp"` in `src/osm/Node.cpp` which made builds on fedora fail with boost 1.76 and gcc 12.1.1
> Add missing header

- apps/osm2rdf-stats.cpp
- include/osm2rdf/config/Config.h
- include/osm2rdf/geometry/Relation.h
- include/osm2rdf/osm/GeometryHandler.h
- include/osm2rdf/osm/LocationHandler.h
- include/osm2rdf/osm/Relation.h
- include/osm2rdf/osm/RelationHandler.h
- src/config/Config.cpp
- src/osm/FactHandler.cpp
- src/osm/GeometryHandler.cpp
- src/osm/LocationHandler.cpp
- src/osm/OsmiumHandler.cpp
- src/osm/Relation.cpp
- src/osm/RelationHandler.cpp
- src/osm/Way.cpp
- src/util/DirectedGraph.cpp
- tests/geometry/Relation.cpp
- tests/osm/FactHandler.cpp
In this PR we add the "boost/version.hpp" header in all files checking boost version. It happened on fedora that the config option "--add-relation-envelope" was not found even though boost 1.78 is installed.
This PR also contains some minor code cleanup in various places, mostly small renames which should not alter the behavior.
> Add "boost/version.hpp" header in all files checking boost version and minor clean up

- include/osm2rdf/osm/GeometryHandler.h
- src/osm/GeometryHandler.cpp
- tests/osm/GeometryHandler.cpp
@lehmann-4178656ch, I have to open another PR for this branch - I noticed that the symmetric intersect relations are wrong for ways - if `WAY INTERSECTS_AREA AREA`, then we should write `AREA INTERSECTS_NONAREA WAY`, not `AREA INTERSECTS_AREA WAY`. This PR fixes this.
> Fix symmetric intersect and contains relation

- src/config/Config.cpp
Order in enum GeoTriplesMode: none = 0, reduced = 1, full = 2
Old order in modeStrings: none, full, reduced
New order in modeStrings: none, reduced, full
> Fix mismatch between `modeStrings` and `GeoTriplesMode`

- include/osm2rdf/osm/GeometryHandler.h
- src/osm/GeometryHandler.cpp
- tests/osm/GeometryHandler.cpp
This reduces the memory footprint as better algorithmic solutions are now implemented and the (huge) lookup-table has now next to no benefit on speed but a huge memory penality.
> Remove obsolete nodedata

- include/osm2rdf/config/Config.h
- include/osm2rdf/config/Constants.h
- include/osm2rdf/osm/Way.h
- src/config/Config.cpp
- src/osm/FactHandler.cpp
- src/osm/Way.cpp
- tests/E2E.cpp
- tests/config/Config.cpp
- tests/osm/FactHandler.cpp
- tests/osm/Way.cpp
Dump ways which represent areas only as MULTIPOLYGON.
Add option to restore the old behavior by adding LINESTRING representations explicitly.
> Area linestring remove

- include/osm2rdf/osm/Relation.h
- src/osm/FactHandler.cpp
- src/osm/Relation.cpp
In https://github.com/ad-freiburg/osm2rdf/commit/efc743168ccd9aad62a926666bd87261e63f9e37, we fixed the issue of areas always having two geometries (the area POLYGON, and the original way linestring).
This PR introduceds this behavior for relations also. Here, a simply check whether the polygon has `type=boundary` or `type=multipolygon` suffices.
This should fix this issue, again raised in https://github.com/ad-freiburg/qlever/issues/1217
> Do not output GEOMETRYCOLLECTION geometry for relations which are areas

- include/osm2rdf/osm/GeometryHandler.h
- include/osm2rdf/util/DirectedAcyclicGraph.h
- include/osm2rdf/util/DirectedGraph.h
- src/osm/GeometryHandler.cpp
- src/osm/OsmiumHandler.cpp
- src/util/DirectedGraph.cpp
- tests/osm/GeometryHandler.cpp
The latest `planet.osm` run for https://osm2rdf.cs.uni-freiburg.de failed because the OOM killer killed `osm2rdf` during the fast-lookup preparation of the reduced DAG.
I implemented the following things to (hopefully) reduce the memory usage during this stage. Until this PR is merged, **this branch is used for the weekly builds**.
1.  Use a `std::map` to hold both the adjacency lists and the fast lookup cache (a bit slower, but lower memory overhead than `std::unordered_map`)
2.   Better scoping during DAG build to destroy the temporary full DAG before the fast lookup processing is started on the new reduced graph. Previously, the complete *unreduced* temporary DAG together with its fast lookup cache was still in memory during the fast lookup preparation on the *reduced* DAG. Now, the …
> Reduce memory usage during DAG build

- include/osm2rdf/osm/GeometryHandler.h
- src/osm/GeometryHandler.cpp
For the named area contains relation, we use an approximate *contains* relation. Its slack has so far been hardcoded. It makes sense to makes this configurable. The first commit in this PR adds a variable `APPROX_CONTAINS_SLACK` in `GeometryHandler.h`.
This is particularly important as we currently cannot build the OpenHistoricalMap dataset (see https://github.com/ad-freiburg/qlever/issues/1220) with an approximate contains relation. Basically, the problem is that for some administrative areas, we have many versions which differ only **slightly**. If the difference is within the allowed slack, none of our existing speedup heuristics are effective (they notice that we are not contained, but do not abort as we *might* be approximately contained), and we must compute a full intersection of …
> Make approximate contains slack configurable

- include/osm2rdf/config/Config.h
- include/osm2rdf/config/Constants.h
- include/osm2rdf/osm/CountHandler.h
- include/osm2rdf/osm/OsmiumHandler.h
- include/osm2rdf/util/ProgressBar.h
- src/config/Config.cpp
- src/osm/CountHandler.cpp
- src/osm/OsmiumHandler.cpp
* Extend first pass to count number of osm objects
* Calculate number of tasks to handle these objects - areas are not known at this point in time and not added to the task count!
* Use finished tasks as progress indicator for second pass instead of read bytes
> Improve progress bar for second pass

- include/osm2rdf/osm/GeometryHandler.h
- src/osm/GeometryHandler.cpp
This PR removes duplicate `ogc:` triples when `writeTransitiveClosure` is used. It does not fix duplicate triples which are generated in `dumpNamedAreaRelations`.
> First step fixing duplicate ogc triples

- include/osm2rdf/config/Config.h
- include/osm2rdf/config/Constants.h
- include/osm2rdf/osm/FactHandler.h
- include/osm2rdf/osm/GeometryHandler.h
- include/osm2rdf/osm/Node.h
- include/osm2rdf/osm/Relation.h
- include/osm2rdf/osm/Way.h
- include/osm2rdf/ttl/Constants.h
- src/config/Config.cpp
- src/osm/FactHandler.cpp
- src/osm/GeometryHandler.cpp
- src/osm/Node.cpp
- src/osm/Relation.cpp
- src/osm/Way.cpp
- src/ttl/Writer.cpp
- tests/issues/Issue24.cpp
- tests/osm/FactHandler.cpp
- tests/ttl/Writer.cpp
This PR improves the support for OHM. It addresses among other things:
* Configurable `approx_contains_slack` with different default values for OHM (`0`) and OSM (`0.05`)
* #69 
* prefix names mentioned in ad-freiburg/qlever#1220
* basic support for `start_date` and `end_date` mentioned in ad-freiburg/qlever#1220
> Improve OHM support

- include/osm2rdf/config/Config.h
- include/osm2rdf/config/Constants.h
- src/config/Config.cpp
- src/osm/FactHandler.cpp
- tests/E2E.cpp
- tests/issues/Issue15.cpp
- tests/issues/Issue24.cpp
- tests/osm/FactHandler.cpp
- tests/ttl/Writer.cpp
This removes the ambiguity introduced with ad-freiburg/osm2rdf#24 which resurfaced in ad-freiburg/qlever#1219
> Remove --hasgeometry-as-wkt

- README.md
We missed to remove this note during our work on #81 .
> Remove note on --hasgeometry-as-wkt from Readme

- src/osm/GeometryHandler.cpp
If the outer geometry is exactly equivalent to the input geometry, we do not store an outer geometry. Instead, an empty outer geometry is stored. In areaIntersectsArea(), however, the check whether one of the two geometries has an empty outer geometry was missing. An empty area does not intersect any other area, so the outer geometry check always returned false in such cases, even if the original geometries intersected (as areas are not checked for contains if they do not intersect, this also lead to missing contains relations).
This PR fixes this behavior.
This issue was found be comparing the output of `spatialjoin` to the output of `osm2rdf`. [This query](https://qlever.cs.uni-freiburg.de/osm-planet/4NGHSq) by Hannah lists all geometries that are marked as *contained in Freiburg* by …
> Check if outer geometry is empty in areaIntersectsArea().

- include/osm2rdf/osm/FactHandler.h
- src/osm/FactHandler.cpp
- tests/osm/FactHandler.cpp
This PR changes the behavior of the `start_date` and `end_date` writing behavior: if the `xsd:YearMonth` or `xsd:YearMonthDay` object would contain a month or a day outside the allowed range (1-12, 1-31, resp.), don't output it.  It also adds some tests for this behavior.
I noticed that we output invalid values here while testing https://github.com/ad-freiburg/osm2rdf/pull/58. During the E2E test, the TTL validation via QLever rightfully complains:
10:24:52 WARN  riot            :: [line: 9961932, col: 40] Lexical form '1831-18' not valid for datatype XSD gYearMonth
> Check allowed ranges for xsd:YearMonth and xsd:YearMonthDay triples

- src/osm/FactHandler.cpp
- tests/osm/FactHandler.cpp
For ways, the centroid, the convex hull, the envelope and the oriented bounding box were written without checking whether the way was an area. These triples were then again written for the area. Without the centroids, we never noticed the duplicate triples, as they were always equivalent. For the centroids, however, this is no longer the case, as the mean of all points on a line typically greatly differs from the mean of all points in a polygon bounded by that line.
This PR fixes this behavior.
> Fix double writing of centroids, convex hull, envelope and oriented bounding box for areas derived from ways

- src/osm/OsmiumHandler.cpp
- tests/issues/Issue15.cpp
- tests/osm/OsmiumHandler.cpp
So far, we are completely skipping untagged ways, as these are almost always inner rings of polygonal areas, and will appear in the geometry of the respective relation. However, some meta information (for example, their node members) is lost this way.
There are only around 21 M untagged ways in the entire OSM dataset, which is less than 2 % of all ways. With this PR, osm2rdf handles untagged ways in exactly the same manner as tagged ways.
> Also handle untagged ways

- include/osm2rdf/config/Config.h
- include/osm2rdf/config/Constants.h
- include/osm2rdf/osm/CountHandler.h
- src/config/Config.cpp
- src/osm/CountHandler.cpp
- src/osm/OsmiumHandler.cpp
This PR adds the options `--no-untagged-nodes`, `--no-untagged-ways`, `--no-untagged-relations` and `--no-untagged-areas`. This is motivated by the fact that `osm2rdf` takes too long for the weekly updated dumps on https://osm2rdf.cs.uni-freiburg.de with the new default of writing *all* nodes to the output and considering them for the geometric relations. This is not our fault, the BZ2 compression simply takes so long.
As soon as this PR is merged, I will add `--no-untagged-nodes` to the command line of the weekly dumps.
> Options for untagged entities

- include/osm2rdf/config/Constants.h
- src/config/Config.cpp
This PR fixes a typo in the `--help` text for `--output-compression` (which has listed `gz2` as a valid argument, but the supported argument is actually `gz`). It also changes the behavior when an unknown argument is supplied: previously, it silently fell back to `bz2`, with this PR, an error is thrown.
> Fix issues with option `--output-compression`

- apps/osm2rdf.cpp
This PR updates `libspatialjoin` to allow parallel sweepline event sorting, see https://github.com/ad-freiburg/util/commit/cd1721ddcc5498a8bce08624ce4bef9da60ef5d0
> Parallel sweepline event sorting 

- src/osm/GeometryHandler.cpp
This PR fixes some issues with `hasCentroid` for smaller polygons. For such objects, the previous approach ran into numerical stability issues. Some centroids where more than 10 meters off; compare some centroids in [this query](https://qlever.cs.uni-freiburg.de/petrimaps/?query=PREFIX+geo%3A+%3Chttp%3A%2F%2Fwww.opengis.net%2Font%2Fgeosparql%23%3E+PREFIX+osmkey%3A+%3Chttps%3A%2F%2Fwww.openstreetmap.org%2Fwiki%2FKey%3A%3E+PREFIX+ogc%3A+%3Chttp%3A%2F%2Fwww.opengis.net%2Frdf%23%3E+PREFIX+osmrel%3A+%3Chttps%3A%2F%2Fwww.openstreetmap.org%2Frelation%2F%3E+SELECT+%3Fosm_id+%3Fhasgeometry+WHERE+%7B+osmrel%3A1960198+ogc%3AsfContains+%3Fosm_id+.+%3Fosm_id+geo%3AhasCentroid%2Fgeo%3AasWKT+%3Fhasgeometry+.+%3Fosm_id+osmkey%3Abuilding+%3Fbuilding+%7D&backend=https%3A%2F%2Fqlever.cs.uni-freiburg.de%2Fapi …
> Fix centroids for small polygons

- .github/workflows/docker-build-bz2.yml
- .github/workflows/docker-build-gz.yml
- .github/workflows/docker-build-stdout.yml
- .github/workflows/docker-build-uncompressed.yml
- .github/workflows/native-build.yml
- Dockerfile
- include/osm2rdf/config/Config.h
- include/osm2rdf/config/Constants.h
- src/config/Config.cpp
- src/osm/FactHandler.cpp
- tests/issues/Issue24.cpp
- tests/osm/FactHandler.cpp
So far, for each geometry, its centroid, axis-parallel bounding box, oriented bounding box, and convex hull were output by default. There was an option `--no-add-centroids`, but there was no option for the other three. Now, none of these features are added by default, and there are individual options to add each of them, namely (note the singular, the old option used the plural):
`--add-centroid`, `--add-envelope`, `--add-obb`, and `--add-convex-hull`.
While at it, also no longer output the `osm2rdf:facts` triple when the value is zero, that is, do not output it for untagged nodes, ways, relations, and areas. Note that when the other `osm2rdf:facts` triples are present (which they are by default), the value `0` can be inferred by the triple not being present for a geometry. If the output …
> No longer add centroid, envelope, obb, convex hull by default
